### ISSUE TITLE
Search fails when multiple words are entered in search field

### ISSUE THREAD

**Issue by kekukui** [segler-alex/kodi-radio-browser#15]
**If multiple words are entered in Search field, an unhandled exception occurs:**

```
ERROR: EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 400: Bad Request
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.audio.radiobrowser/main.py", line 216, in <module> data = downloadFile(url, None)
File "/storage/.kodi/addons/plugin.audio.radiobrowser/main.py", line 57, in downloadFile response = urllib2.urlopen(req)
File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
File "/usr/lib/python2.7/urllib2.py", line 435, in open
File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
File "/usr/lib/python2.7/urllib2.py", line 473, in error
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 400: Bad Request
-->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.audio.radiobrowser/?mode=search
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.radiobrowser/?mode=search) failed
```

**Comment by kekukui** [comment]
This issue was fixed in git but 1.1.1 is still not published in the Kodi official repo
